In [438]:
liste = [1,2,3]
import numpy as np

In [439]:
#numpy arry yapmak için 
np.array(liste)

array([1, 2, 3])

In [440]:
#matris oluştırma 
mat = [[1,2,3],[4,2,3],[2,2,2]]
#numpy arry yapmak için
np.array (mat)

array([[1, 2, 3],
       [4, 2, 3],
       [2, 2, 2]])

In [441]:
np.arange(0,200)
#sıfırdan 200 e kadaar gider.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [442]:
np.zeros(6)# 6 tane 0 vektoru oluşturacak 0 olan bir dizi

array([0., 0., 0., 0., 0., 0.])

In [443]:
np.zeros((2,3))#elemanları sıfır olan bir mamtris


array([[0., 0., 0.],
       [0., 0., 0.]])

In [444]:
#elmanları bir olan için ones kullanılır.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [445]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [446]:
#elelmanları 7 olan bir matris
np.ones((2,6))*7

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

In [447]:
np.eye(7)#birim matris

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [448]:
#ragere dizi oluşturma
np.random.rand(3,3)

array([[0.11398436, 0.82868133, 0.04689632],
       [0.62628715, 0.54758616, 0.819287  ],
       [0.19894754, 0.8568503 , 0.35165264]])

In [449]:
np.random.randint(1,100)

89

<h1> pandas seriler </h1>

In [450]:
#pandas veri analizi yapmayı, veri temizlemeyi ... sağlar.
import numpy as np
import pandas as pd

In [451]:
labels = ['a','b','c']
my_data = [10,20,30]
array = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [452]:
pd.Series(array)

0    10
1    20
2    30
dtype: int32

In [453]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [454]:
pd.Series(array, labels)

a    10
b    20
c    30
dtype: int32

In [455]:
pd.Series(d) #sözlük verildi

a    10
b    20
c    30
dtype: int64

In [456]:
seri1 = pd.Series([6,16,34,35],['ankara', 'bursa', 'istanbul', 'izmir'])

In [457]:
seri1

ankara       6
bursa       16
istanbul    34
izmir       35
dtype: int64

In [458]:
import numpy as np
import pandas as pd
#data frame hem x hemde y de veri tutan veri tablisu

In [459]:
np.random.seed(10)

In [460]:
df = pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'], ['W','X','Y','Z'])
# pd.DataFrame(data,index x, index y)


In [461]:
df

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [462]:
df['W']

a    1.331587
b    0.621336
c    0.004291
d   -0.965066
e   -1.136602
Name: W, dtype: float64

In [463]:
df['Z']

a   -0.008384
b    0.108549
c    1.203037
d    0.445138
e   -1.079805
Name: Z, dtype: float64

In [464]:
df[['W','Z']]

W         Z
a  1.331587 -0.008384
b  0.621336  0.108549
c  0.004291  1.203037
d -0.965066  0.445138
e -1.136602 -1.079805

In [465]:
#yeni sutun oluşturma
df['yeni'] = df['W'] + df['Z']

In [466]:
df

W         X         Y         Z      yeni
a  1.331587  0.715279 -1.545400 -0.008384  1.323203
b  0.621336 -0.720086  0.265512  0.108549  0.729884
c  0.004291 -0.174600  0.433026  1.203037  1.207329
d -0.965066  1.028274  0.228630  0.445138 -0.519928
e -1.136602  0.135137  1.484537 -1.079805 -2.216407

In [467]:
#sutun silme
df.drop('yeni', axis = 1, inplace = True)
#inplace değişikliğin kalıcı olduğunu belitmek için.


In [468]:
df.drop('e')

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138

In [469]:
df

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [470]:
df.loc['a'] # satırı seri yapmak için

W    1.331587
X    0.715279
Y   -1.545400
Z   -0.008384
Name: a, dtype: float64

In [471]:
df.iloc[2] #satır göstermek için

W    0.004291
X   -0.174600
Y    0.433026
Z    1.203037
Name: c, dtype: float64

In [472]:
df>0


W      X      Y      Z
a   True   True  False  False
b   True  False   True   True
c   True  False   True   True
d  False   True   True   True
e  False   True   True  False

In [473]:
booldf = df>0

In [474]:
booldf

W      X      Y      Z
a   True   True  False  False
b   True  False   True   True
c   True  False   True   True
d  False   True   True   True
e  False   True   True  False

In [475]:
df[booldf]

W         X         Y         Z
a  1.331587  0.715279       NaN       NaN
b  0.621336       NaN  0.265512  0.108549
c  0.004291       NaN  0.433026  1.203037
d       NaN  1.028274  0.228630  0.445138
e       NaN  0.135137  1.484537       NaN

In [476]:
df

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [477]:
df['W']>0

a     True
b     True
c     True
d    False
e    False
Name: W, dtype: bool

In [478]:
df[df['W']>0] #nan lar alımaz

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037

In [479]:
df[df['W']> 0] [['Y', 'Z']]

Y         Z
a -1.545400 -0.008384
b  0.265512  0.108549
c  0.433026  1.203037

In [480]:
df[(df['W']>0)&( df['Z']>1)]

W       X         Y         Z
c  0.004291 -0.1746  0.433026  1.203037

In [481]:
df[(df['W']>0)|( df['Z']>1)]

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037

In [482]:
df.reset_index()

index         W         X         Y         Z
0     a  1.331587  0.715279 -1.545400 -0.008384
1     b  0.621336 -0.720086  0.265512  0.108549
2     c  0.004291 -0.174600  0.433026  1.203037
3     d -0.965066  1.028274  0.228630  0.445138
4     e -1.136602  0.135137  1.484537 -1.079805

In [483]:
df

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [484]:
sehir = 'adana kars van osmaniye hatay '.split()

In [485]:
sehir

['adana', 'kars', 'van', 'osmaniye', 'hatay']

In [486]:
df['sehir'] = sehir

In [487]:
df

W         X         Y         Z     sehir
a  1.331587  0.715279 -1.545400 -0.008384     adana
b  0.621336 -0.720086  0.265512  0.108549      kars
c  0.004291 -0.174600  0.433026  1.203037       van
d -0.965066  1.028274  0.228630  0.445138  osmaniye
e -1.136602  0.135137  1.484537 -1.079805     hatay

In [488]:
df.set_index('sehir')

W         X         Y         Z
sehir                                           
adana     1.331587  0.715279 -1.545400 -0.008384
kars      0.621336 -0.720086  0.265512  0.108549
van       0.004291 -0.174600  0.433026  1.203037
osmaniye -0.965066  1.028274  0.228630  0.445138
hatay    -1.136602  0.135137  1.484537 -1.079805

In [489]:
df

W         X         Y         Z     sehir
a  1.331587  0.715279 -1.545400 -0.008384     adana
b  0.621336 -0.720086  0.265512  0.108549      kars
c  0.004291 -0.174600  0.433026  1.203037       van
d -0.965066  1.028274  0.228630  0.445138  osmaniye
e -1.136602  0.135137  1.484537 -1.079805     hatay

In [490]:
import numpy as np
import pandas as pd

In [491]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1, 2, 3, 1, 2, 3]
heir_index = list(zip(outside, inside))
heir_index_mul = pd.MultiIndex.from_tuples(heir_index)


In [492]:
df = pd.DataFrame(np.random.randn(6,2),heir_index_mul,['A','B']) 

In [493]:
df 

A         B
G1 1 -1.977728 -1.743372
   2  0.266070  2.384967
   3  1.123691  1.672622
G2 1  0.099149  1.397996
   2 -0.271248  0.613204
   3 -0.267317 -0.549309

In [494]:
df.loc['G1'].loc[1] 

A   -1.977728
B   -1.743372
Name: 1, dtype: float64

In [495]:
df.index.names = ['GRUP','SAYI']

In [496]:
df

A         B
GRUP SAYI                    
G1   1    -1.977728 -1.743372
     2     0.266070  2.384967
     3     1.123691  1.672622
G2   1     0.099149  1.397996
     2    -0.271248  0.613204
     3    -0.267317 -0.549309

In [497]:
#dataFrame den kod alma eski yöntem
df.loc['G1']

A         B
SAYI                    
1    -1.977728 -1.743372
2     0.266070  2.384967
3     1.123691  1.672622

In [498]:
#yeni yöntem
df.xs('G1')

A         B
SAYI                    
1    -1.977728 -1.743372
2     0.266070  2.384967
3     1.123691  1.672622

In [499]:
df

A         B
GRUP SAYI                    
G1   1    -1.977728 -1.743372
     2     0.266070  2.384967
     3     1.123691  1.672622
G2   1     0.099149  1.397996
     2    -0.271248  0.613204
     3    -0.267317 -0.549309

In [500]:
df.xs(1,level = 'SAYI')

A         B
GRUP                    
G1   -1.977728 -1.743372
G2    0.099149  1.397996

<h1> pandas data frame kayıp veriler </h1>

In [501]:
import numpy as np
import pandas as pd

In [502]:
d ={'A': [1,2,np.nan], 'B':[np.nan,3,np.nan], 'C':[4,5,6]}

In [503]:
df = pd.DataFrame(d)

In [504]:
df

A    B  C
0  1.0  NaN  4
1  2.0  3.0  5
2  NaN  NaN  6

In [505]:
df.dropna() #nan olanları satırları siliyor

A    B  C
1  2.0  3.0  5

In [506]:
df.dropna(axis=1) #içerisinde kayıp plan sutunları siler.

C
0  4
1  5
2  6

In [507]:
df.dropna(thresh = 2)#eşik değeri
#bir satırın silinmesi için içinde en az 2 tane nan olması gerek

A    B  C
0  1.0  NaN  4
1  2.0  3.0  5

In [508]:
#kayıp verileri doldurmak için fillna kullanılır.
df.fillna(value='nisanur')
#nan olan yerlere nisanur yazdırdım.

A        B  C
0      1.0  nisanur  4
1      2.0      3.0  5
2  nisanur  nisanur  6

<h3> groupby</h3>

In [509]:
import numpy as np
import pandas as pd

In [510]:
data = {'Şirket':['TURKCELL','TURKCELL','VODAFONE','VODAFONE','TTELEKOM','TTELEKOM'],
        'Kişi':['mehmet','büşra','selim','caner','gamze','merve'],
        'Satış':[250,325,152,645,468,525]}

In [511]:
df = pd.DataFrame(data)

In [512]:
df

Şirket    Kişi  Satış
0  TURKCELL  mehmet    250
1  TURKCELL   büşra    325
2  VODAFONE   selim    152
3  VODAFONE   caner    645
4  TTELEKOM   gamze    468
5  TTELEKOM   merve    525

In [513]:
sirket = df.groupby('Şirket')
sirket.mean()#ortslsmsdını dönderir

C:\Users\nisan\AppData\Local\Temp\ipykernel_13936\209201000.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sirket.mean()#ortslsmsdını dönderir


Satış
Şirket         
TTELEKOM  496.5
TURKCELL  287.5
VODAFONE  398.5

In [514]:
sirket.sum()

C:\Users\nisan\AppData\Local\Temp\ipykernel_13936\1695508158.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sirket.sum()


Satış
Şirket         
TTELEKOM    993
TURKCELL    575
VODAFONE    797

In [515]:
sirket.std()

C:\Users\nisan\AppData\Local\Temp\ipykernel_13936\881909338.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sirket.std()


Satış
Şirket              
TTELEKOM   40.305087
TURKCELL   53.033009
VODAFONE  348.603643

In [516]:
sirket.sum().loc('TURKCELL')

C:\Users\nisan\AppData\Local\Temp\ipykernel_13936\693834221.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sirket.sum().loc('TURKCELL')


ValueError: No axis named TURKCELL for object type DataFrame

In [517]:
df.groupby('Şirket').count()

Kişi  Satış
Şirket               
TTELEKOM     2      2
TURKCELL     2      2
VODAFONE     2      2

In [518]:
df.groupby('Şirket').min()

Kişi  Satış
Şirket                
TTELEKOM  gamze    468
TURKCELL  büşra    250
VODAFONE  caner    152

In [519]:
df.groupby('Şirket').max()

Kişi  Satış
Şirket                 
TTELEKOM   merve    525
TURKCELL  mehmet    325
VODAFONE   selim    645

In [520]:
df.groupby('Şirket').describe()

Satış                                                        
         count   mean         std    min     25%    50%     75%    max
Şirket                                                                
TTELEKOM   2.0  496.5   40.305087  468.0  482.25  496.5  510.75  525.0
TURKCELL   2.0  287.5   53.033009  250.0  268.75  287.5  306.25  325.0
VODAFONE   2.0  398.5  348.603643  152.0  275.25  398.5  521.75  645.0

birleştirme işlemleri


In [521]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [522]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [523]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [524]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [525]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [526]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [527]:
pd.concat([df1,df2,df3])
#df lerin boyurları aynı olmalı

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [528]:
pd.concat([df1,df2,df3], axis= 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11