In [59]:
import pandas as pd

In [60]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [61]:
seri = pd.Series([1,2,3,4])
type(seri)

pandas.core.series.Series

In [62]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [63]:
seri.size

4

In [64]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [65]:
seri.dtype

dtype('int64')

In [66]:
seri.ndim

1

In [67]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [68]:
seri.head(7)

0    1
1    2
2    3
3    4
dtype: int64

In [69]:
seri.tail(2)

2    3
3    4
dtype: int64

#index isimlendirmesi

In [70]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [71]:
pd.Series([99,22,332,94,5], index=[1,4,5,6,7])

1     99
4     22
5    332
6     94
7      5
dtype: int64

In [72]:
pd.Series([99,22,332,94,5], index=["a","w","k","q","t"])

a     99
w     22
k    332
q     94
t      5
dtype: int64

In [73]:
seri = pd.Series([99,22,332,94,5], index=["a","w","k","q","t"])
seri["w"]
seri["a":"k"]

a     99
w     22
k    332
dtype: int64

#sözlük üzerinden seri oluşturmak

In [74]:
sozluk={"reg":10,"log":12,"car":22}



In [75]:
seri=pd.Series(sozluk)

In [76]:
seri

reg    10
log    12
car    22
dtype: int64

serileri tek bir veri olarak kabul et.

In [77]:
pd.concat([seri,seri])

reg    10
log    12
car    22
reg    10
log    12
car    22
dtype: int64

elaman işlemleri

In [78]:
import numpy as np
a = np.array([1,2,3,43,45,232])
seri = pd.Series(a)
seri

0      1
1      2
2      3
3     43
4     45
5    232
dtype: int32

In [79]:
seri[3]

43

In [80]:
seri[0:3:2]

0    1
2    3
dtype: int32

In [81]:
seri = pd.Series([121,12,2], index=["reg","ar","arw"])
seri

reg    121
ar      12
arw      2
dtype: int64

In [82]:
seri.index

Index(['reg', 'ar', 'arw'], dtype='object')

In [83]:
seri.keys

<bound method Series.keys of reg    121
ar      12
arw      2
dtype: int64>

In [85]:
list(seri.items())

[('reg', 121), ('ar', 12), ('arw', 2)]

In [86]:
seri.values

array([121,  12,   2], dtype=int64)

In [87]:
"reg" in seri

True

pandas dataframe oluşturma

In [88]:
import pandas as pd

In [89]:
l = [1,2,39,67,90]

In [90]:
l

[1, 2, 39, 67, 90]

In [91]:
pd.DataFrame(l,columns=["degısken_ismi"])

degısken_ismi
0              1
1              2
2             39
3             67
4             90

In [92]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
pd.DataFrame(m, columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

#df isimlendirme

In [95]:
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [103]:
df.columns=("deg1","deg2","deg3")

df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [111]:
type(df)
df.axes
df.shape
df.ndim
df.size
df.values
type(df.values)
df.tail(7)

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

eleman işlemleri
